### ISSUE TITLE
Upgrade all providers to 0.15.0 compliance

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/capability-providers#12]
The redis, NATS, and http server providers are being upgraded since they're used with the integration tests. all other capability providers need to be upgraded to 0.15.x compatibility:

* Support health checks
* Ensure that binding operation is idempotent
* Support generated data types - do **NOT** use the wascc codec for anything other than the plugin trait.
* Support the `stop` function in the 0.9.0 codec / plugin definition and ensure that this stop function can't panic

**Comment by brooksmtownsend** [comment]
Once #32 and #33 are closed, this issue can be closed.
