### ISSUE TITLE
Create a NATS-based (replication) in-memory key-value provider

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/capability-providers#13]
The current implementation of lattice's internal cache replication mechanism has been ad hoc and patchwork up to this point. To formalize this, we're planning on refactoring the host to communicate with its distributed cache over a key-value capability provider. The default provider should be "zero friction" and "just work", therefore since NATS is required for lattice anyway, using simple state replication and query over NATS provides a _reasonable default_. Developers and platform builders can choose to swap out for more powerful or specific feature set providers as their needs demand.

The development of this key value provider is designed to support the closing of the following two issues in the main wasmCloud repository:
* [https://github.com/wasmCloud/wasmCloud/issues/21](https://github.com/wasmCloud/wasmCloud/issues/21)
* [https://github.com/wasmCloud/wasmCloud/issues/33](https://github.com/wasmCloud/wasmCloud/issues/33)

**Comment by brooksmtownsend** [comment]
Closed via #15
