### ISSUE TITLE
Rename keyvalue contract ID to use wasmcloud prefix

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/capability-providers#14]
Rename `wascc:keyvalue` to `wasmcloud:keyvalue` for all key-value capability providers. The new actor interface uses this new contract ID.

**Comment by brooksmtownsend** [comment]
Fairly sure this was closed with #23 , am I missing another provider that implements `wascc:keyvalue`? @autodidaddict

**Comment by autodidaddict** [comment]
There's an in-memory cache provider in the examples repo. Did we get that one?

**Comment by brooksmtownsend** [comment]
Nope, haven't updated that one yet. I'll get a PR in for it and reference this issue

**Comment by brooksmtownsend** [comment]
This was closed with the above mentioned PR
