### ISSUE TITLE
Vault KV provider should support certs not supplied by absolute file paths

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/capability-providers#190]
Right now the KV vault provider has a `certs` variable in link definition that allows you to define a set of certificates to use for vault authentication. The problem is that this field expects the certs to be file system paths. This is an issue because capability providers should not make assumptions about where they're being run, and so we need a way to specify certs that involves _only_ using the link definition information _or_ the provider configuration JSON payload (startup)

**Comment by jcuffe** [comment]
Interested in helping out here, quick question: could this be done by modifying the `vaultrs` crate to first check if the provided value represents the contents of a valid PEM certificate [here](https://docs.rs/vaultrs/latest/src/vaultrs/client.rs.html#101)?
