### ISSUE TITLE
[BUG] NATS provider does not close connections on `delete_link`

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/capability-providers#196]
The code in https://github.com/wasmCloud/capability-providers/blob/main/nats/src/main.rs#L229-L237 makes an assumption that dropping the struct closes the subscription but with testing we've been able to see that the subscription stays alive. This might also result in duplicate subscribers if you re-create the link

**Comment by vados-cosmonic** [comment]
hey @brooksmtownsend I'd like to take a stab at this -- digging into the `nats.rs` docs and I can't find an explicit close/disconnect...

**Comment by brooksmtownsend** [comment]
Fixed with #205
