### ISSUE TITLE
Blobstore fs provider doesn't sanitize user provided paths

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/capability-providers#200]
This is not a full security issue because the FS provider is more of a testing provider, but we should probably close things off. If you look at [the code](https://github.com/wasmCloud/capability-providers/blob/main/blobstore-fs/src/main.rs#L120-L121), you'll see we just accept object IDs without sanitation, so I could pass `../../../../../lookatme` to escape from the specified "ROOT" variable. We should be sanitizing paths, even though this is more of a test provider

**Comment by vados-cosmonic** [comment]
Hey @thomastaylor312 I'd like to take a look at this -- I'm thinking I'll resolve the paths absolutely then make sure they never attempt to travel above the root directory.
