### ISSUE TITLE
Document async nats dependency conflict

### ISSUE THREAD

**Issue by stephenandary** [wasmCloud/capability-providers#209]
All upgrades except for async_nats are upgradable without breaking changes. 

Async_Nats will cause issues with several lines due to similar naming of structs in newest version and may need to be set more explicitly in future: 

```
while let Some(msg) = subscription.next().await {
                let span = tracing::debug_span!("handle_message", actor_id = %link_def.actor_id);
                span.in_scope(|| {
                    wasmbus_rpc::otel::attach_span_context(&msg); <=== SEVERAL AREAS IN CODE WITH REFS LIKE THIS
                });
                let permit = match semaphore.clone().acquire_owned().await {
                    Ok(p) => p,
                    Err(_) => {
                        warn!("Work pool has been closed, exiting queue subscribe");
                        break;
                    }
                };
                tokio::spawn(dispatch_msg(link_def.clone(), msg, permit).instrument(span));
            }
 ```
 ```
 mismatched types
`async_nats::Message` and `async_nats::message::Message` have similar names, but are actually distinct types
perhaps two different versions of crate `async_nats` are being used?
```

**Comment by thomastaylor312** [comment]
Those actually _are_ the same types. If you look at the docs, `async_nats::Message` is just an export of `async_nats::message::Message`. This is the common problem we've been trying to solve with mixed versions of nats between wasmbus-rpc using one version of async nats and the provider using another. https://github.com/wasmCloud/weld/pull/135 is one way we are trying to improve it. So the compiler is actually right that there are two different versions at play

**Comment by stephenandary** [comment]
This is great to know, thank you.

**Comment by thomastaylor312** [comment]
@stephenandary Did you want me to keep this open or are we ok to close it?

**Comment by stephenandary** [comment]
Is the dependency ceiling documented somewhere? Can cargo deps be updated to indicate this?

**Comment by thomastaylor312** [comment]
Not sure what you mean by cargo deps being updated to indicate this, but no, this particular problem isn't documented. Might be worth adding as a doc task for this provider at least

**Comment by stephenandary** [comment]
I mean indicating in the dependency that it must be equal to or below a certain version. 

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#comparison-requirements

**Comment by thomastaylor312** [comment]
The default in cargo when none is specified is only patch releases when pre-1.0 and then minor and patch for post-1.0

**Comment by stephenandary** [comment]
It was a minor update that caused breaking changes.

**Comment by stephenandary** [comment]
While that is good for cargo, it is not very indicative to a user.

**Comment by thomastaylor312** [comment]
It only really matters for devs of the NATS capability provider. I definitely wouldn't say no to a PR making it explicit, but I don't think it is a requirement here

**Comment by stephenandary** [comment]
I agree, not a requirement. Just makes it more obvious when someone sees there is a significant minor version delta and analyzer loves to put a big red x to entice you to upgrade lol. I am currently working with a different messaging provider to test something, if the tests work out I can revisit this if I remember.
