### ISSUE TITLE
Create Random Value Generator Provider as Alternative to Numbergen Builtin

### ISSUE THREAD

**Issue by stephenandary** [wasmCloud/capability-providers#227]
The consensus from WasmCloud Wed on 26 Apr 2023 is to use a provider to generate cryptographically secure values, as the numbergen builtin can't and should not be used for crypto purposes. 

Until wasi-crypto can be investigated properly - https://github.com/WebAssembly/wasi-crypto - create an initial iteration on a provider that can be used to produce generated values that are cryptographically secure. 

The current game plan is to leverage a crate such as the Rand Crate, using CSPRNG algorithms (possibly ChaCha20 or HC128) <https://rust-random.github.io/book/guide-rngs.html#cryptographically-secure-pseudo-random-number-generators-csprngs>

**Comment by ricochet** [comment]
The wasifill proposed in https://github.com/wasmCloud/wasmCloud/issues/315 will likely rely on this provider.

**Comment by stephenandary** [comment]
@ricochet, can I touch base with you when I start working on this so I know if there is anything I need to keep in mind for wasifills? I don't know anything about those.

**Comment by ricochet** [comment]
Absolutely.

See also https://github.com/bytecodealliance/wasmtime/tree/main/crates/wasi-crypto for implementation. 

The neato thing about the wasifills trick is that if you write a provider as you normally would, we can basically polyfill directly to that from the wasmCloud host.

**Comment by stephenandary** [comment]
@jordan-rash mentioned algorithm used should align with FIPs, so ChaCha20 is unacceptable. HC128 is still an option, and Jordan has done some work with openssl::rand that may be a good option.

**Comment by stephenandary** [comment]
When building the interface, I was hoping to try: https://github.com/wasmCloud/weld/tree/main/smithy-bindgen, so if building the interface and using this, can you ping me so I can learn along also?

**Comment by stephenandary** [comment]
Standards to primarily follow should now be ISO 19790:2012 and ISO 24759:2017. 

FIPS now refers to those standards for security requirements.

FIPS 140-3 should still be referenced for any additional security requirements that may have been included by NIST beyond those ISO standards.

**Comment by stephenandary** [comment]
OASIS standards have PKCS #11 which specifies a platform-independent application programming interface (API) for cryptographic tokens which store and control authentication information including personal identity, cryptographic keys, certificates, digital signatures, and biometric data.

This is an open source standard, and as such is easier to leverage than ISO standards. Comparison should probably be concidered. To save time and money it may be worth starting with this though. 

http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html

**Comment by stephenandary** [comment]
No longer have time for this one, moving onto other work.

**Comment by stephenandary** [comment]
Closing issue and suggest using API like Random.org instead. I have been using it for myself and it's great.
