### ISSUE TITLE
[BUG] Cannot put URI with NATS provider

### ISSUE THREAD

**Issue by ricochet** [wasmCloud/capability-providers#231]
This is a bug in the provider's default initialization logic for URIs. The `DEFAULT_URI` is not overridden by the passed in URI.

NATS provider version 0.17.0

Log output: `provider initialization or put-link: NATS connection to 0.0.0.0:4222 `

**Comment by vados-cosmonic** [comment]
Hey @ricochet I think I'll take this one on, should be pretty simple
