### ISSUE TITLE
httpserver should have a "readonly" mode that can be used when it is only being used to serve up files or responses

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/capability-providers#237]
This is the same thing as https://github.com/wasmCloud/examples/issues/217, but in the provider where it belongs. This should probably be a value on the linkdef called `FILESERVER_MODE` with a boolean value

**Comment by connorsmith256** [comment]
$0.02: I would prefer `GETONLY_MODE` or `READONLY_MODE` over specific references to a "fileserver"

**Comment by thomastaylor312** [comment]
I'm good with `READONLY_MODE`

**Comment by brooksmtownsend** [comment]
Closed with https://github.com/wasmCloud/capability-providers/pull/243
