### ISSUE TITLE
[BUG] Capability providers require glibc

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/capability-providers#265]
Currently-released capability providers depend on glibc at runtime, which is redundant, since these are Rust programs with no runtime C dependencies.

Dependency on glibc prevents these binaries from running on various operating systems, e.g. Alpine Linux, the oh-so-popular OCI container image base, in turn making wasmCloud useless on platforms that do not have glibc installed (and causing runtime failures, which are difficult to debug)

Instead, the capability providers should be statically-linked using e.g. musl toolchain

**Comment by brooksmtownsend** [comment]
@rvolosatovs I know you said you would look into fixing this, per my last comment on the wasmCloud PR I'd just like this to be a solution that doesn't take too much effort as a developer to deal with. I'd love to get the solution here built into "wash build" and we've historically had difficulties building musl providers. Let me know if there's any other context I can add

**Comment by rvolosatovs** [comment]
> @rvolosatovs I know you said you would look into fixing this, per my last comment on the wasmCloud PR I'd just like this to be a solution that doesn't take too much effort as a developer to deal with. I'd love to get the solution here built into "wash build" and we've historically had difficulties building musl providers. Let me know if there's any other context I can add

I believe the consensus so far was to move all providers to https://github.com/wasmCloud/wasmCloud and set up CI as part of that effort, which would build static, portable binaries.

In fact, the providers are already built and most of that logic would just be reused.

Not sure how `wash build` is related here, but I am happy to update that tool to build static binaries as well

**Comment by brooksmtownsend** [comment]
> Not sure how wash build is related here, but I am happy to update that tool to build static binaries as well

Though it doesn't do it yet, the plan was to have wash build also compile capability providers and then sign them, resulting in the final provider archive. Complexities around compiling for different targets is the primary reason why this isn't implemented yet

**Comment by rvolosatovs** [comment]
> Stalebot reminded me to read through this again, and I want to call out:
> 
> Removing glibc from our 1st-party providers is great, but in order for the wasmCloud ecosystem to fully support distros like Alpine, we also need to provide a way for every developer to build their 3rd-party provider in a way that doesn't require glibc

Sure, but I am not sure how that is relevant here. If one can build for linux-gnu, then it's much more likely than not that they can build for linux-musl as well.

**Comment by connorsmith256** [comment]
In https://github.com/wasmCloud/wasmCloud/pull/620 we switched to a Debian-based container for the host to include glibc. If we change our 1st-party CD to build providers against musl, we might think it it's okay to switch back to a scratch container. What I was trying to convey above is: unless we can control how users build their own providers and guarantee all providers are built against musl, we still need the host images to include glibc

**Comment by rvolosatovs** [comment]
> In https://github.com/wasmCloud/wasmCloud/pull/620 we switched to a Debian-based container for the host to include glibc. If we change our 1st-party CD to build providers against musl, we might think it it's okay to switch back to a scratch container. What I was trying to convey above is: unless we can control how users build their own providers and guarantee all providers are built against musl, we still need the host to run on a system with glibc (in docker, and natively)

Apart from backwards-compatibility reasons, I think we should provide Debian-based images indefinitely, since that generally is the common practice in the ecosystem. Whether or not the Debian-based image should be the default, however, especially in the world where majority of providers are Wasm components running in WASI is up to discussion.
