### ISSUE TITLE
README.md broken wasmcloud contract links

### ISSUE THREAD

**Issue by msftph** [wasmCloud/capability-providers#266]
Some of the contract links on the main README.md are broken:

https://github.com/wasmCloud/capability-providers/blob/main/README.md#first-party-capability-providers

The blob store links point to a "-fs" and "-s3" folder in the 'interfaces' repo, which don't exist. The lattice controller link should be 'lattice-control'

| current | expected |
| --------| -----------|
|https://github.com/wasmCloud/interfaces/tree/main/blobstore-fs|https://github.com/wasmCloud/interfaces/tree/main/blobstore|
|https://github.com/wasmCloud/interfaces/tree/main/blobstore-s3|https://github.com/wasmCloud/interfaces/tree/main/blobstore|
|https://github.com/wasmCloud/interfaces/tree/main/lattice-controller|https://github.com/wasmCloud/interfaces/tree/main/lattice-control|

**Comment by connorsmith256** [comment]
Thank you for the call-out @msftph !
