### ISSUE TITLE
[BUG] in httpclient:0.8.0 provider

### ISSUE THREAD

**Issue by royaljain** [wasmCloud/capability-providers#270]
httpclient:0.8.0 has a bug 

Description: 

1. Doesn't create a link even with linkdef defined in wadm.yaml
2. Even if you create the link manually, there's a 500 Internal Server error when you try to run 

How to reproduce:
 
1. Run the example actors in wasmCloud/examples repo - animal-image-downloader works with httpclient:0.7.0 (default), xkcd doesn't with httpclient:0.8.0 (default). If you replace this with httpclient:0.7.0 then xkcd works well. 

Have confirmed this with a custom example - httpclient:0.7.0 works while httpclient:0.8.0 gives 500 Internal Server error. Logs didn't help much "wasmcloud:bus/host.call`: failed to call linked provider: unknown actor call alias"

**Comment by brooksmtownsend** [comment]
Thanks for filing this @royaljain , would you mind putting your version of `wash` and `wasmcloud` here so we can try and reproduce? If you are running wasmCloud via `wash`, you should be able to find that version by checking the help text of `wash up --help` and looking for `wasmcloud_version`

**Comment by royaljain** [comment]
Sure, 

wash 0.20.2
wasmcloud-version default: v0.78.0-rc6

Btw, really interesting project

**Comment by brooksmtownsend** [comment]
@royaljain I was unable to reproduce this with the stable v0.78.0 version of wasmcloud, would you mind checking with
```
WASMCLOUD_VERSION=v0.78.0 wash up
```

when you get a chance? I'll try and cut a release of `wash` with the non-rc version now 😄
