### ISSUE TITLE
Upgrade telnet provider to 0.15.0 compliance

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/capability-providers#32]
The `telnet` provider needs to:

- [ ] Support health checks
- [ ] Ensure that binding operation is idempotent
- [ ] Support generated data types in [actor-interfaces](https://github.com/wasmCloud/actor-interfaces/) - do NOT use the wascc codec for anything other than the plugin trait.
- [ ] Support the stop function in the 0.9.0 codec / plugin definition and ensure that this stop function can't panic
- [ ] Use the `wasmcloud:telnet` capability contract ID
- [ ] Update `Cargo.toml` and `README.md` to the standard that the other capabilities set, with README badges, license information, descriptions, etc.

**Comment by stevelr** [comment]
This should be completed with the actix2 pr: https://github.com/wasmCloud/capability-providers/pull/51
