### ISSUE TITLE
Merge this repository into actor-interfaces

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/capability-providers#69]
In an effort to simplify our repositories, I suggest we merge capability-providers into our [actor-interfaces](https://github.com/wasmCloud/actor-interfaces) repository and rename the repo to something like `capabilities`. I feel like this would be great for a few reasons:
1. Fewer repositories to keep track of
2. Reduces the surface area for an incoming community member
3. Easier to test newer versions of providers and interfaces with relative dependencies

The ideal version of the `capabilities` repository would be a one-stop-shop for anyone looking to utilize our resources in their wasmcloud project. For example, if someone has a need for a keyvalue capability for their project, they are able to navigate to the `capabilities` repository and find the interface AND our implementations to immediately use.

Example file structure:
```
capabilities (repo)/
├─ keyvalue/
│  ├─ assemblyscript/
│  ├─ go/
│  ├─ rust/
│  ├─ providers/
│  │  ├─ inmemory/
│  │  ├─ redis/
│  ├─ keyvalue.widl
├─ blahblahrootrepostuff
├─ README.md
```
A slightly flatter structure:
```
capabilities (repo)/
├─ keyvalue/
│  ├─ assemblyscript/
│  ├─ inmemory/
│  ├─ go/
│  ├─ redis/
│  ├─ rust/
│  ├─ keyvalue.widl
├─ blahblahrootrepostuff
├─ README.md
```
Personally, I think I'm a fan of the first one as it doesn't mix and match our providers and interfaces, but I'd like to propose both for feedback.

Additionally, for this merge, we're going to have to take special care to organize our Github Actions for both projects. For both capability-providers and actor-interfaces we have an action for the build and release of each artifact. It will likely be worth some effort thinking on how we can consolidate some of these actions or at least organize them in the `.github/workflows/` directory better.

cc @jordan-rash @autodidaddict @billyoung @ChrisRx for some feedback 🙂

**Comment by jordan-rash** [comment]
So there might be a play here using the tags in the PR.  Depending on our ability to restrict access to certain tags, we could using something like `build` or `release` to trigger the actions. Also, we could look into the matrix thing to keep the actions list from getting too big.  I recommend we (I can do it) open an issue and table out when we want certain actions to happen and what events should trigger those.  Maybe we need a repo for where our policies and standards are going to live (if we don't already have one)

**Comment by brooksmtownsend** [comment]
Yeah with the two combined it's showing the need for us to formally spec out the way that our actions trigger. A matrix build/release would help immensely if we can do it in a way that doesn't build every interface and provider every time 😛

**Comment by brooksmtownsend** [comment]
I think the build should happen on every PR and merge into main whenever a specific interface or provider is modified, and I think that release should be something that we can trigger easily. Perhaps release could happen on merge to main instead of a tag, the interfaces and providers are small enough that I think we'd want to publish any fixes immediately. Thoughts @ChrisRx @autodidaddict ?

**Comment by autodidaddict** [comment]
I'm not a fan of inconsistency. If we release by tagging in all of our other repositories, then we should do so in this one as well. If combining repositories means that we'll be forced to not use tags to release, then maybe we need to reconsider the merger. I'm not the CI expert, but I'm hoping we'll be able to find a clean way to release what we need to from this new ultra-super-mega repository cleanly.

**Comment by brooksmtownsend** [comment]
I think tags will still work fine, but we should incorporate some kind of scripting to make it easier. A Makefile or a helper bash script would be enough

**Comment by stevelr** [comment]
I think we decided against this - keep actor-interfaces with just the idl definition and library-generated code, and capability providers separate.

**Comment by brooksmtownsend** [comment]
@stevelr I'm fine with keeping them separate as long as we have an easy way to discover the concrete implementations of those actor interfaces (e.g. link to the implementation in the interface-level README) because if I was an app developer browsing the interfaces repo, I'd like to see what options I had for implementations.

If we're on the same page you can go ahead and close this issue
